[package]
name = "tinshell"
version = "0.1.0"
authors = ["Tinfold"]

[dependencies]
colored = "2.0.0"
crossterm = "*"
ctrlc = "3.4.0"
path-slash = "0.2.1"
ratatui = "*"
shlex = "1.1.0"

[[bin]]
name="tinshell"
path="src/main.rs"

[[bin]]
name="edit"
path="src/edit/src/edit.rs"
